name: 'Terraform GKE Deploy'

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    
    # AQUÍ ESTÁ EL TRUCO: Terraform mapea TF_VAR_nombre a variable "nombre"
    env:
      TF_VAR_project_id: "landing-dev-zafa"
      TF_VAR_region: "europe-west1"
      TF_VAR_host_project_id: "landing-host-zafa"
      TF_VAR_vpc_name: "vpc-kubernetes"
      TF_VAR_sa_id: "sa-gke-nodes"
      TF_VAR_vpc_self_link: "https://www.googleapis.com/compute/v1/projects/landing-host-zafa/global/networks/vpc-kubernetes"
      TF_VAR_subnet_standard_self_link: "https://www.googleapis.com/compute/v1/projects/landing-host-zafa/regions/europe-west1/subnetworks/subnet-gke-standard"
      TF_VAR_subnet_autopilot_self_link: "https://www.googleapis.com/compute/v1/projects/landing-host-zafa/regions/europe-west1/subnetworks/subnet-gke-autopilot"

    defaults:
      run:
        working-directory: ./environments/dev

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Google Auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/932038588586/locations/global/workloadIdentityPools/github-pool-zafa/providers/github-provider'
          service_account: 'github-actions-deployer@landing-dev-zafa.iam.gserviceaccount.com'

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Plan'
        # Comando limpio gracias a las variables de entorno (env)
        run: terraform plan -input=false -lock=false

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false -lock=false